angular.module('ts-form-templates', []).run(['$templateCache', function($templateCache) {
  $templateCache.put("templates/checkbox-element.tpl.html",
    "<div class=\"form-group\"> <label for=\"{{ vm.element.getId() }}\" class=\"control-label col-sm-3\"> {{ vm.element.getLabel() }} </label> <div class=\"col-sm-9\"> <div class=\"checkbox\"> <label for=\"{{ vm.element.getId() }}\"> <input id=\"{{ vm.element.getId() }}\" type=\"checkbox\" ng-true-value=\"{{ vm.element.getTrueValue() }}\" ng-false-value=\"{{ vm.element.getFalseValue() }}\" ng-model=\"vm.modelValue\"> </label> </div> </div> </div>");
  $templateCache.put("templates/input-element.tpl.html",
    "<div class=\"form-group\" ng-class=\"{ 'has-error' : vm.form.title.$invalid && vm.form.title.$touched }\"> <label for=\"{{ vm.element.getId() }}\" class=\"control-label col-sm-3\"> {{ vm.element.getLabel() }} </label> <div class=\"col-sm-9\"> <input id=\"{{ vm.element.getId() }}\" type=\"text\" class=\"form-control\" ng-model=\"vm.modelValue\" ng-minlength=\"{{ vm.element.getMinLength() }}\" ng-maxlength=\"{{ vm.element.getMaxLength() }}\" ng-required=\"{{ vm.element.getRequired() }}\"> <div ng-messages=\"vm.form.title.$error\" ng-show=\"vm.form.title.$invalid && vm.form.title.$touched\" class=\"help-block\"> <div ng-messages-include=\"ui-messages.tpl.html\"></div> </div> </div> </div>");
  $templateCache.put("templates/password-element.tpl.html",
    "<div class=\"form-group\"> <label for=\"{{ vm.element.getId() }}\" class=\"control-label col-sm-3\"> {{ vm.element.getLabel() }} </label> <div class=\"col-sm-9\"> <input id=\"{{ vm.element.getId() }}\" type=\"password\" class=\"form-control\" ng-model=\"vm.modelValue\" ng-minlength=\"{{ vm.element.getMinLength() }}\" ng-maxlength=\"{{ vm.element.getMaxLength() }}\" ng-required=\"{{ vm.element.getRequired() }}\"> </div> </div>");
  $templateCache.put("templates/select-element.tpl.html",
    "<div class=\"form-group\"> <label for=\"{{ vm.element.getId() }}\" class=\"control-label col-sm-3\"> {{ vm.element.getLabel() }} </label> <div class=\"col-sm-9\"> <select id=\"{{ vm.element.getId() }}\" name=\"{{ vm.element.getId() }}\" class=\"form-control\" ng-model=\"vm.modelValue\" ng-options=\"option.value as option.label for option in vm.element.getOptions()\"></select> </div> </div>");
  $templateCache.put("templates/textarea-element.tpl.html",
    "<div class=\"form-group\"> <label for=\"{{ vm.element.getId() }}\" class=\"control-label col-sm-3\"> {{ vm.element.getLabel() }} </label> <div class=\"col-sm-9\"> <textarea id=\"{{ vm.element.getId() }}\" type=\"text\" class=\"form-control\" ng-model=\"vm.modelValue\" ng-minlength=\"{{ vm.element.getMinLength() }}\" ng-maxlength=\"{{ vm.element.getMaxLength() }}\" ng-required=\"{{ vm.element.getRequired() }}\"></textarea> </div> </div>");
}]);
